version: '3.9'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack-full
    network_mode: bridge
    ports:
      - "4566:4566"
      - "8080:8080"
    environment:
      - SERVICES=s3
      - LAMBDA_EXECUTOR=local
      - LAMBDA_REMOTE_DOCKER=false
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  app:
    container_name: serverless-app
    build: .
    #command: npm test
    volumes:
      - .:/src
      - nodemodules:/src/node_modules
    restart: on-failure
    ports:
      - 3000:3000
    links:
      - localstack
    depends_on:
      - localstack
    environment:
      LOCALSTACK_HOST: localstack
      S3_PORT: 4566

volumes:
  nodemodules: {}
