service: serverless-template
frameworkVersion: '>=2.41.2'

package:
  excludeDevDependencies: true
  individually: true
  exclude:
    - ./mock
    - ./seed

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  stage: ${opt:stage, 'local'}
  region: ${self:custom.config.region}
  memorySize: 128
  apiGateway:
    shouldStartNameWithService: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:ListStreams
        - dynamodb:DescribeStream
      Resource:
        - 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.database.userRewardsTable}'
        - 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.database.userRewardsTable}/index/*'
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    USER_REWARDS_TABLE: ${self:custom.database.userRewardsTable}
    REGION: ${self:provider.region}
    STAGE: ${self:provider.stage}
    CORS_ALLOW_ORIGIN: ${self:custom.config.cors.ALLOW_ORIGIN}
    CORS_ALLOW_HEADERS: ${self:custom.config.cors.ALLOW_HEADERS}
    CORS_ALLOW_METHODS: ${self:custom.config.cors.ALLOW_METHODS}

custom:
  config: ${file(./stages/index.stage.yml):${opt:stage, self:provider.stage}}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  splitStacks:
    custom: ./stacks-map.ts
    perFunction: false
    perType: false
    perGroupFunction: false
  customDomain:
    domainName: ${self:custom.config.domainName}
    apiType: rest
    basePath: signup
    certificateName: '*.higoralves.dev'
    createRoute53Record: false
    endpointType: 'regional'
    securityPolicy: tls_1_2
  database:
    userRewardsTable: ${self:service}-${self:provider.stage}-user-rewards
  dynamodb:
    stages:
      - local
      - test
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      userRewards:
        sources:
          - table: ${self:custom.database.userRewardsTable}
            sources: [ './seed/userRewardsTable.json' ]
  localstack:
    stages:
      - local
    autostart: false #disable localstack when deploying
  prune:
    automatic: true
    number: 3
  jest:
    preset: ts-jest
    bail: 1
  serverless-offline:
    useChildProcesses: true

resources:
  Resources:
    Test:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.database.userRewardsTable}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

plugins:
  - serverless-webpack
  - serverless-localstack
  - serverless-dynamodb-local
  - serverless-prune-plugin
  - serverless-jest-plugin
  - serverless-offline
  - serverless-offline-dynamodb-streams
  - serverless-domain-manager
  - serverless-plugin-split-stacks

functions:
  hello:
    handler: src/functions/hello/hello.handler
    events:
      - http:
          path: hello/{id}
          method: get
          cors: true
