org: higoralves
app: serverless-ts
service: serverless
frameworkVersion: '2.41.2'

package:
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'local'}
  lambdaHashingVersion: '20201221'
  region: ${opt:stage, 'us-east-1'}
  memorySize: 256
  environment:
    ${file(./config/env.${self:provider.stage}.json)}

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  prune:
    automatic: true
    number: 3

plugins:
  - serverless-webpack
  - serverless-prune-plugin

functions:
  hello:
    handler: src/functions/hello/hello.hello
