#org: higoralves
#app: serverless-ts
service: serverless
frameworkVersion: '>=2.41.2'

package:
  excludeDevDependencies: true
  individually: true
  exclude:
    - ./mock

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'local'}
  lambdaHashingVersion: '20201221'
  region: ${opt:stage, 'us-east-1'}
  memorySize: 256
  environment:
    ${file(./config/env.${self:provider.stage}.json)}

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  prune:
    automatic: true
    number: 3
  jest:
    preset: ts-jest
    bail: 1
  serverless-offline:
    useChildProcesses: true

plugins:
  - serverless-webpack
  - serverless-localstack
  - serverless-prune-plugin
  - serverless-jest-plugin
  - serverless-offline

functions:
  hello:
    handler: src/functions/hello/hello.hello
    events:
      - http:
          path: hello
          method: get
          cors: true
